/*
Generated by scripts/gen_sprite_data.py at 2025-12-15 02:37:56
Seek head : 256
Memory Offset : 0x200000
*/


#include "graphics/pomelo.h"
#include "drivers/disk.h"
#include "sprites.h"



#define CAT0_SPRITES_MEM 0x200000
u8 *cat0_sprites_data = (u8*)CAT0_SPRITES_MEM;
u32 cat0_sprites_bounding_box_data[32];


#define CAT1_SPRITES_MEM 0x208000
u8 *cat1_sprites_data = (u8*)CAT1_SPRITES_MEM;
u32 cat1_sprites_bounding_box_data[32];


#define CAT2_SPRITES_MEM 0x210000
u8 *cat2_sprites_data = (u8*)CAT2_SPRITES_MEM;
u32 cat2_sprites_bounding_box_data[32];


#define CAT3_SPRITES_MEM 0x218000
u8 *cat3_sprites_data = (u8*)CAT3_SPRITES_MEM;
u32 cat3_sprites_bounding_box_data[32];


#define LEVEL0_SPRITES_MEM 0x220000
u8 *level0_sprites_data = (u8*)LEVEL0_SPRITES_MEM;
u32 level0_sprites_bounding_box_data[160];



struct SpriteSheet cat0_sprites = {
	.width = 128,
	.height = 256,
	.unit_width = 32,
	.unit_height = 32,
	.data = 0x0,
	.sprite_bounding_box = 0x0
};


struct SpriteSheet cat1_sprites = {
	.width = 128,
	.height = 256,
	.unit_width = 32,
	.unit_height = 32,
	.data = 0x0,
	.sprite_bounding_box = 0x0
};


struct SpriteSheet cat2_sprites = {
	.width = 128,
	.height = 256,
	.unit_width = 32,
	.unit_height = 32,
	.data = 0x0,
	.sprite_bounding_box = 0x0
};


struct SpriteSheet cat3_sprites = {
	.width = 128,
	.height = 256,
	.unit_width = 32,
	.unit_height = 32,
	.data = 0x0,
	.sprite_bounding_box = 0x0
};


struct SpriteSheet level0_sprites = {
	.width = 128,
	.height = 320,
	.unit_width = 16,
	.unit_height = 16,
	.data = 0x0,
	.sprite_bounding_box = 0x0
};


void init_sprites() {
			
	load_bytes_to_buffer(cat0_sprites_data, 256, 128*256);
	cat0_sprites.data = cat0_sprites_data;
	compute_spritesheet_bounding_box(&cat0_sprites, cat0_sprites_bounding_box_data);
	cat0_sprites.sprite_bounding_box = cat0_sprites_bounding_box_data;


	load_bytes_to_buffer(cat1_sprites_data, 320, 128*256);
	cat1_sprites.data = cat1_sprites_data;
	compute_spritesheet_bounding_box(&cat1_sprites, cat1_sprites_bounding_box_data);
	cat1_sprites.sprite_bounding_box = cat1_sprites_bounding_box_data;


	load_bytes_to_buffer(cat2_sprites_data, 384, 128*256);
	cat2_sprites.data = cat2_sprites_data;
	compute_spritesheet_bounding_box(&cat2_sprites, cat2_sprites_bounding_box_data);
	cat2_sprites.sprite_bounding_box = cat2_sprites_bounding_box_data;


	load_bytes_to_buffer(cat3_sprites_data, 448, 128*256);
	cat3_sprites.data = cat3_sprites_data;
	compute_spritesheet_bounding_box(&cat3_sprites, cat3_sprites_bounding_box_data);
	cat3_sprites.sprite_bounding_box = cat3_sprites_bounding_box_data;


	load_bytes_to_buffer(level0_sprites_data, 512, 128*320);
	level0_sprites.data = level0_sprites_data;
	compute_spritesheet_bounding_box(&level0_sprites, level0_sprites_bounding_box_data);
	level0_sprites.sprite_bounding_box = level0_sprites_bounding_box_data;

}
		